### ISSUE TITLE
Magnesium Extras don't seem to show up when using Rubidium.

### ISSUE THREAD

**Issue by Romoslayer** [TeamDeusVult/MagnesiumExtras#10]
![2022-04-11_14 14 47](https://user-images.githubusercontent.com/47157784/162835723-d4657039-fec4-4d04-9896-afcd24852123.png)

**Comment by KoinBanks** [comment]
I also have this issue.

**Comment by DigitalWendigo** [comment]
Same. 
The options to lower the entity and tileentity horizontal and vertical render distance don't show up. 
They are however shown in the config file of magnesium extras, but they don't appear ingame.

**Comment by GekidoLukas** [comment]
Yup, nothing shows up, sadly

**Comment by Pierre-PMG** [comment]
Yes I do have the same problem.

**Comment by quentin452** [comment]
> ![2022-04-11_14 14 47](https://user-images.githubusercontent.com/47157784/162835723-d4657039-fec4-4d04-9896-afcd24852123.png)

fixed in v1.4.0 1.16.5
