### ISSUE TITLE
1.18.2 - incompatible with JEI

### ISSUE THREAD

**Issue by zachsai** [TeamDeusVult/MagnesiumExtras#13]
![image](https://user-images.githubusercontent.com/63996164/165685113-edec2c30-1de0-426b-b954-53f0a81b8a23.png)
Jei is not visually showing, but i can click on items where jei would be and recipes are popping up. Ingredients are not showing

**Comment by Gbergz** [comment]
Can report this aswell, items pop up again if you search for something, but if the search bar is blank, nothing shows.
You can click on items on the right but everything's invisible.

**Comment by SpinHarmony** [comment]
I realize this was already answered on Curseforge, but for the benefit of anyone seeing this here, this is an intended feature. JEI will only render ingredients when searching, to improve performance and decrease usage of screen space.

 This is configurable, although at the time of writing this the option hasn’t been added to the video settings menu, but likely will be soon.

**Comment by zachsai** [comment]
Is it intentional that you can still click the non rendered items to show their recipe?

**Comment by SpinHarmony** [comment]
In the 1.16.5 version of TDV Tweaks (which is where the feature was originally located) it does not let you click on non-rendered items, so I would assume that it’s not intended in the 1.18.2 version of Rubidium Extras.

**Comment by ItsHarvey** [comment]
If you open the rubidium_extras.toml you can disable the option for now. It's under the first section of settings.

Just change "Hide JEI Until Searching" = true 

to 

"Hide JEI Until Searching" = false

**Comment by Guinaro** [comment]
May I suggest that this option is disabled by default.
I just created a new modpack and tought JEI wasn't working somehow.
I installed JEI for a reason and didn't expect another mod to simply override basic and expected functionality of JEI.
If not make this option toggleable from in game and also display a warning upon entering a world a start up.

**Comment by aAndrew3030** [comment]
I second that, spent two days trying to fix JEI. It is not expected that a mod would disable the rendering of JEI, and I am not sure why anyone would want that. I assume most would just guess it is a bug with JEI, leading to the JEI team getting unnecessary bug reports.

**Comment by DarkShadow44** [comment]
I have to complain as well, please don't enable this per default - it just leads to confusion.

**Comment by vizthex123** [comment]
same here, very annoying.

here's my game log if the dev is reading: https://gist.github.com/vizthex123/d084f9d69cdda07ee38d7d1b0781df27

**Comment by DarkShadow44** [comment]
@vizthex123 No log needed, just disable the feature.

**Comment by vizthex123** [comment]
> @vizthex123 No log needed, just disable the feature.

i just uninstalled the mod, less hassle that way. Hope it gets fixed, but if not it's not a huge loss.

**Comment by rmnaderdev** [comment]
> May I suggest that this option is disabled by default. I just created a new modpack and tought JEI wasn't working somehow. I installed JEI for a reason and didn't expect another mod to simply override basic and expected functionality of JEI. If not make this option toggleable from in game and also display a warning upon entering a world a start up.

I back this, lots of people are getting confused. It would make sense to either disable this feature by default or at least have some indication near where the JEI interface is that it is disabled by this mod.

It has already been false-reported as a bug in JEI: https://github.com/mezz/JustEnoughItems/issues/2900

**Comment by oliverrook** [comment]
I just tried disabling this in the config, and now JEI fails to show up entirely after crashing the game on world load the first time.![2022-07-24_17 12 57](https://user-images.githubusercontent.com/1887407/180666031-4d4a2825-b4f2-4130-805a-1b2972682a22.png)


In fact, JEI crashed and is no longer usable after doing this.
