### ISSUE TITLE
[1.18.2] Unpredictable rendering error crash

### ISSUE THREAD

**Issue by The-Arcanian** [TeamDeusVult/MagnesiumExtras#15]
Game crashes with a rendering error at unpredictable times, though most often on world load.

My suspects are:
Magnesium/Rubidium Extras
Rubidium
Pollution of the realms

But I am starting here.

[Crash log](https://gist.github.com/The-Arcanian/da16dce190e442f96e83296a965775bd)

**Comment by txnitxnichopper** [comment]
Not an Extras issue.
