### ISSUE TITLE
Strings should use localization system

### ISSUE THREAD

**Issue by yezhiyi9670** [TeamDeusVult/MagnesiumExtras#17]
Any strings displayed on the UI should use Minecraft localization system (has the corresponding string value in `assets/
magnesium_extras/lang/en_us.json`), but it's not the case in this mod.

**Comment by qznfbnj** [comment]
I couldn't agree more.
![6DB425C0A5CF9956B42E0E61E691FF26](https://user-images.githubusercontent.com/100760086/177547743-07a845c5-f64d-435a-b188-c839d50502bc.jpg)

**Comment by txnitxnichopper** [comment]
PR it if you want it. I speak english and write in english.
