### ISSUE TITLE
Zoom configs missing in 1.18.2 with Rubidium

### ISSUE THREAD

**Issue by Nhaaro** [TeamDeusVult/MagnesiumExtras#18]
**Forge 40.1.0 | Minecraft 1.18.2 | rubidium-0.5.2a | rubidium_extras-1.18.2_v1.3.1 | Launcher CurseForge**

All the zoom configurations seem to be missing from the settings menu
![image](https://user-images.githubusercontent.com/41486028/174922107-833d9379-9148-4fb4-8082-fcc9a803e3c5.png)
![image](https://user-images.githubusercontent.com/41486028/174923029-da212484-9d2a-4add-88c0-3d378da50e16.png)

The zoom key works just fine, but cannot be configured to use things like smooth zoom

**Comment by txnitxnichopper** [comment]
I used a different zoom mod for the 1.18.2 port. Didn't have those options.

**Comment by Riyuukii** [comment]
I had the same issue with rubidium_extras-1.19.2_v1.4.3 , modifying the config file for smooth zoom is also not working. Is there any alternative for smooth zoom? Ok Zoomer (Forge) stopped working once rubidium-extras is installed.
