### ISSUE TITLE
Zoom causes JourneyMap waypoints to blink

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [TeamDeusVult/MagnesiumExtras#21]
I'm having a problem pressing the zoom button, which causes the Journey Map waypoints to flash on the screen even though I don't look at them.

**Comment by txnitxnichopper** [comment]
Not an Extras issue. Zoom simply reduces your FOV

**Comment by CapivaraTupiniquim** [comment]
It was a bug, the JournelMap waypoints fished and I couldn't move the camera with the zoom, but it doesn't happen anymore in recent versions.
