### ISSUE TITLE
please update version 1.16.5

### ISSUE THREAD

**Issue by papillo12** [TeamDeusVult/MagnesiumExtras#22]
in the latest versions of rubidium although the mod still works (I think) it no longer appears to configure it in video settings for example to deactivate the fps view.
![Captura de pantalla 2022-07-16 072841](https://user-images.githubusercontent.com/80440525/179356860-c8781369-a213-4bbb-b644-cf9ee0042814.png)

**Comment by AugustSaintFreytag** [comment]
I noticed the same issue, it works well but can not be configured.

**Comment by LordSamosa** [comment]
Also running in to this, thought I had installed the wrong one 😅

**Comment by quentin452** [comment]
> in the latest versions of rubidium although the mod still works (I think) it no longer appears to configure it in video settings for example to deactivate the fps view. ![Captura de pantalla 2022-07-16 072841](https://user-images.githubusercontent.com/80440525/179356860-c8781369-a213-4bbb-b644-cf9ee0042814.png)

settings fixed in v1.4.0 1.16.5
