### ISSUE TITLE
[1.16.5] rubidium-0.2.10 crash when i entering in worlds with magnesium/rubidium extra installed

### ISSUE THREAD

**Issue by quentin452** [TeamDeusVult/MagnesiumExtras#31]
rubidium 0.2.10 make crash with magnesium/rubidium extra installed , when i use rubidium 0.2.9 with magnesium/rubidium extra not make crash

Forge version : 36.2.39
minecraft version : 1.16.5
mods list :
rubidium 0.2.10
magnesium_extras-mc1.16.5_v1.3.1

steps to reproduce :

1 : make a world
2 : watch crash

crash report : [crash-2022-08-25_00.34.19-client.txt](https://github.com/Asek3/Rubidium/files/9419850/crash-2022-08-25_00.34.19-client.txt)
logs :[latest.log](https://github.com/Asek3/Rubidium/files/9419849/latest.log)

**Comment by OcrSu** [comment]
[crash.txt](https://github.com/TeamDeusVult/MagnesiumExtras/files/9428770/crash.txt)
maybe its the same crash

**Comment by quentin452** [comment]
fixed in V1.4.0

**Comment by RobertHDPotatoes** [comment]
This seems to have fixed another long standing crash upon launch I had with Rubidium, where I was unable to even track down the mod causing the crash. Thank you for the update!
