### ISSUE TITLE
Create Windmill sails appear to jerk at about 3+ chunks of distance

### ISSUE THREAD

**Issue by gglobensky** [TeamDeusVult/MagnesiumExtras#33]
When I'm close to my windmill (around 3 chunks or less), the windmill sails rotate normally but as soon as I get farther, the sails seem to jerk or rotate really fast.

If I remove Rubidium Extras, the sails act normally.

Thanks for the amazing work!

**Comment by txnitxnichopper** [comment]
fixed.
