### ISSUE TITLE
[Suggestion] Distant Horizons true darkness support

### ISSUE THREAD

**Issue by MarioSMB** [TeamDeusVult/MagnesiumExtras#36]
Currently the "True Darkness" setting does not apply to the LOD models added by Distant Horizons, giving a very poor transition from real terrain to LOD at night. It would be great if the true darkness effect could be applied to LOD terrain as well, thanks!

**Comment by txnitxnichopper** [comment]
This would be something they'd have to add on their end.

**Comment by MrFastZombie** [comment]
For anyone wanting to track this issue on their end, there are several issues opened for this on the Distant Horizons issue tracker:
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/516
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/383
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/278
