### ISSUE TITLE
CRASH: Apparent incompatibility with "Snow real magic mod"

### ISSUE THREAD

**Issue by Doming3000** [TeamDeusVult/MagnesiumExtras#37]
No matter how hard I try, I can't enter any world without my game crashing with the same crash report.

Snow real magic mod: https://www.curseforge.com/minecraft/mc-mods/snow-real-magic
Crash report: [crash-2023-01-10_22.57.15-client.txt](https://github.com/TeamDeusVult/MagnesiumExtras/files/10388335/crash-2023-01-10_22.57.15-client.txt)

**Comment by txnitxnichopper** [comment]
Not my mod.

**Comment by Doming3000** [comment]
Bruh, likewise I stopped needing this mod months ago, I didn't even remember posting this, lol.
