### ISSUE TITLE
FPS counter crash

### ISSUE THREAD

**Issue by PikachuGabe** [TeamDeusVult/MagnesiumExtras#42]
modpack: chroma endless
[crash-2023-03-25_18.40.09-client.txt](https://github.com/TeamDeusVult/MagnesiumExtras/files/11070572/crash-2023-03-25_18.40.09-client.txt)
the line "at net.minecraftforge.client.gui.ForgeIngameGui.handler$bck000$render(ForgeIngameGui.java:898) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinIngameGui,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}" lead me to assume its the FPS counter,based on it referencing the frame counter mixin
magnesium extras version: magnesium_extras-mc1.16.5_v1.4.0.jar
rubidium version: rubidium-0.2.11.jar
magnesium version: magnesium-1.5.jar
magnesium/rubidium dynamic lights version dynamiclightsreforged-mc1.16.5_v1.0.1.jar incase that is of use

**Comment by Kasualix** [comment]
Are you serious? to install Magnesium and Rubidium together?

**Comment by PikachuGabe** [comment]
Dynamic lights and extras are marked as dependents in magnesium relations on CF and extras is marked as a dependent in rubidium relations in CF so CF automatically installed both rubidium and magnesium when i tried to get extras and dynamic lights
In both rubidium and magnesium they are marked as required dependents so to install extras i need to install rubidium and magnesium according to CF
