### ISSUE TITLE
[1.19.2] Alt+F3 doesn't display text + Incompatibility with BetterF3

### ISSUE THREAD

**Issue by PaulerLeOne** [TeamDeusVult/MagnesiumExtras#47]
Pressing Alt+F3 won't display the F3 text, only the FPS and TPS charts. With BetterF3 installed, it doesn't show anything.

rubidium-0.6.2b
rubidium_extras-1.19.2_v1.3.2
BetterF3-4.0.0-Forge-1.19.2
cloth-config-8.2.88-forge

**Comment by txnitxnichopper** [comment]
this is intentional. F3 menu text rendering interferes with accurate frametime graph measurements

**Comment by TelepathicGrunt** [comment]
@nthxny to be frank, that's a horrifying stance. F3 is used for far more than just tps/fps profiling such as what biome they are at, tags on blocks, registry names of blocks/entities,, etc. Hiding all debug text just for the frametime measurement without an alternative is not good at all.

May I propose that you simply add a new keybind to F3 where clicking say F3 + M activates your F3 mode without the text for accurate measurements? That way players still get their normal debug info they want and then can opt in to your more accurate measuring. You can replace the normal F3 FPS number with some like `(Press 'F3+M' to measure FPS)` so players know right away what the keybind is

**Comment by Nycto97** [comment]
[Suggestion] Mention this somewhere on the mod page

As I spent a long time finding out what mod caused this behavior
