### ISSUE TITLE
[1.20.1] Crash on launch

### ISSUE THREAD

**Issue by MrKashew** [TeamDeusVult/MagnesiumExtras#48]
Crash report accuses better combat and combat role of error, but removing this mode solely allows me to launch with no error. Perhaps incompatibility
[crash-2023-07-01_19.59.38-fml.txt](https://github.com/anthxnymc/MagnesiumExtras/files/11928590/crash-2023-07-01_19.59.38-fml.txt)

**Comment by txnitxnichopper** [comment]
fixed in latest version, but you can also just remove Farsight.
