### ISSUE TITLE
Add entity culling optimization by mechanisms from Create mod

### ISSUE THREAD

**Issue by GitJhopa** [TeamDeusVult/MagnesiumExtras#50]
Add entity culling optimization by mechanisms/blocks/entity from Create mod

**Comment by GitJhopa** [comment]
![image](https://github.com/anthxnymc/MagnesiumExtras/assets/86250668/ce4a4f78-51a3-4a12-8f67-2ca269c2b232)

**Comment by ghost** [comment]
Have the same issue.Block entity culling feature will not work properly if flywheel's 'instancing' or 'batching' engine is enabled.

**Comment by txnitxnichopper** [comment]
it really shouldn't even need culling with flywheel instancing.
