### ISSUE TITLE
Multiplayer chunks not loading correctly since v1.4.0

### ISSUE THREAD

**Issue by villainous-j** [TeamDeusVult/MagnesiumExtras#51]
### Issue
If the view distance client-side is less than the view distance set within `server.properties`, chunks will not load past the login chunks (chunks loaded when logging in). The issue doesn't occur in v1.3.2.

Client's logs will show many instances of this error:

`Ignoring chunk since it's not in the view range`

### Testing instructions

- Set the server's view distance to 8
- Set the client's view distance to 2
- Travel in a single direction at least 3 chunks

### Versions tested
1.4.0 and 1.4.1, Forge 1.19.2 - 43.2.14

**Comment by Dylan-McGrory** [comment]
Can also confirm that this is happening with v1.4.1 in 1.20 using Forge 46.0.14

**Comment by txnitxnichopper** [comment]
fixed in latest version.
