### ISSUE TITLE
Zoom not using cinematic camera

### ISSUE THREAD

**Issue by Breadabix** [TeamDeusVult/MagnesiumExtras#7]
Im trying to get the zoom to use the cinematic camera mode so its like optifine zoom, but whatever of the 3 options I use (OFF, VANILLA, MULTIPLIED) it doesnt act like the cinematic camera. Is there another setting that can affect this or is this a bug?

**Comment by SirOMGitsYOU** [comment]
> Im trying to get the zoom to use the cinematic camera mode so its like optifine zoom, but whatever of the 3 options I use (OFF, VANILLA, MULTIPLIED) it doesnt act like the cinematic camera. Is there another setting that can affect this or is this a bug?

I don't believe this is currently implemented, it would be great if something like this could be implemented!
