### ISSUE TITLE
GPU Hard crash on Linux with AMDGPU drivers

### ISSUE THREAD

**Issue by zack-emmert** [TeamDeusVult/MagnesiumExtras#8]
I'm running into graphical corruption issues when running custom 1.16.5 modpack I'm putting together which cause the entire system to freeze, necessitating a hard reboot of the entire machine. I can start up the game, play for about a minute or two, then my monitor briefly loses signal, before visuals return looking like [this]( https://i.imgur.com/s9eYdSa.jpeg). At this point, the system requires a hard reboot to restore functionality. I can only reproduce this with Magnesium (or Rubidium) and Magnesium Extras installed.

I'm running fully updated Arch Linux with an AMD RX 580 GPU. I've observed this issue on both Wayland and X.org, with both linux and linux-lts kernels with systemd-based initramfs, and with both mesa and mesa-git packages.

Here's my full mods list: [mods.txt](https://github.com/TeamDeusVult/MagnesiumExtras/files/8323887/mods.txt).

**Comment by zack-emmert** [comment]
I discovered that I was able to switch to a different TTY after the GPU crash, and I was left with a semi-usable system. I was able to acquire a dmesg log that I've included here:
[dmesg.log](https://github.com/TeamDeusVult/MagnesiumExtras/files/8326819/dmesg.log).

**Comment by txnitxnichopper** [comment]
Not an Extras issue.
